### PR TITLE
georgiev... please look into this.

### PR DESCRIPTION
**Pull request by ghost**
Hi,

I just made some changes to get it work with newer rubygems version. could you please check this. thank you.

### CODE REVIEW

**Comment by georgiev** [comment]
The Diff says: "Showing 66 changed files with 12,434 additions and 0 deletions." - this doesn't look nice to me. Something is wrong here, can you try to submit a more cleaner pull request?

**Comment by georgiev** [comment]
Alternatively - you can try my rails31 branch and see if it fixes your issues (I'm planing the rails31 merge for the next week)

**Comment by ghost** [comment]
yes, sorry I became confused and mixed it up with another firebiry ruby library. I am now really confused: None of the libraries really works in the end.

**Comment by georgiev** [comment]
'gem install rubyfb" should work

**Comment by ghost** [comment]
hey, yes that finally worked, thanks for the hint! :)

**Pull request closed without merging**
